title: "Dylan's Blog"
author: Dylan Ing
email: ding@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Thank you for visiting Dylan's blog. If you have any questions or concerns, please contact him.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ingdyl # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
